  
# # 服务器前置任务(ubuntu使用)
- name: Pre_tasks of Kafka
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
<<<<<<< HEAD
=======
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
>>>>>>> 7885c5e548b9a78da608ec0e4066e141d2cf35aa


# # 核心任务

- name: Kafka
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: cloud, tags: "cloud"} 
    - { role: kafka, tags: "kafka"}
    - { role: end, tags: "end"}